- .gitignore
- app/config/config.py
- app/database/session.py
- requirements.txt
> [feat] dotenv 설정

- .github/workflows/cicd.yml
- appspec.yml
- scripts/start.sh
- [x} Build (빌드 관련)
---
- S3 코드 업로드
- CodeDeploy로 업로드
---
github actions - workflow 추가
code deploy - appspec.yml 추가
EC2용 배포 스크립트 적용 - start.sh 추가
---
[set] github action 세팅 #7
> [set/#7] 백엔드 EC2 배포 완료

- app/models/voice.py
- app/routers/api.py
- app/routers/voice.py
- app/routers/voices.py
- app/schemas/voice.py
- app/services/chat_service.py
- app/services/voice_service.py
- [ 0] Feat(기능 추가)
---
---
---
> [feat/#8]  보이스 삭제기능 추가 했습니당!!

- app/models/__init__.py
- app/models/bubble.py
- app/models/character.py
- app/models/chat.py
- app/models/image.py
- app/routers/voices.py
- app/schemas/voice.py
- app/services/chat_service.py
- app/services/voice_service.py
---
모든 목소리 목록 조회 기능 구현
---
- 기존 read_voices를 read_voices_by_chat으로 변경
- get_voices를 read_voices_by_chat_id로 변경
- response_model을 List[VoiceBase]에서 VoiceBaseList로 변경
- 스키마에 VoiceBaseList 추가
- 저장된 모든 voice 목록을 조회하는 read_voices 추가
- relationship 추가
```python
def get_voices(db: Session, skip: int = 0, limit: int = 100):
voices = db.query(Voice).offset(skip).limit(limit).all()
voice_details = [VoiceDetail(
id=voice.id,
chat_id=voice.bubble.chat_id,
character=voice.bubble.chat.character.name,
bubble_id=voice.bubble_id,
audio_url=voice.audio_url,
content=voice.content,
created_at=voice.created_at.isoformat()
) for voice in voices]
return voice_details
```
사용하면 쿼리문 없이 역참조를 해서 찾을 수 있음
- __init__.py 파일 작성
- SQLAlchemy가 각 모델을 인식하고 관계를 …
> [feat/#9] 모든 목소리 목록 조회 기능 구현

- app/models/bubble.py
- app/models/image.py
- app/routers/images.py
- app/routers/voices.py
- app/schemas/image.py
- app/services/image_service.py
---
발췌 이미지 전체 목록 조회 및 채팅방 별 조회
---
- relationship() 관계 설정
- 발췌 이미지 조회를 위한 router, schema, service 코드 작성
---
> [feat/#12] 발췌 이미지 전체 목록 조회 및 채팅방 별 조회

- app/models/character.py
- app/routers/chats.py
- app/schemas/chat.py
- app/services/character_service.py
- app/services/chat_service.py
---
채팅방 생성 기능
캐릭터 이름 확인
---
- 채팅방 생성 기능 추가
- 캐릭터 이름 유효 확인
- 요청값 유효 확인
---
https://github.com/2024-SummerBootcamp-Team/backend/issues/26
> [feat/#13] 채팅방 생성 기능 추가

- app/Dockerfile
- docker-compose.yml
---
docker watch 세팅
---
1. 처음 실행 시 빌드 부터
```bash
docker compose build
```
2. watch 실행
```bash
docker compose watch
```
---
> set: docker watch 세팅

- app/database/session.py
- app/requirements.txt
- app/routers/chats.py
- app/schemas/chat.py
- app/services/chat_service.py
- [ 0] Feat(기능 추가)
---
feat: character_name 추가
---
---
> [feat/#10] 채팅방 정보조회 response body에 character_name 추가

- app/config/langChain/chatMessageHistory.py
- app/config/langChain/langChainSetting.py
- app/routers/chats.py
- app/services/bubble_service.py
- app/test/langChainTest.py
---
LangChain 임시 구현
---
RunnableWithMessageHistory와 llm 사용을 구현
---
feat/#19
> set: LangChain 채팅 저장 임시구현

- app/config/aws/s3Client.py
- app/routers/images.py
- app/services/bubble_service.py
---
채팅 기능 추가 완료 / 이미지 업로드 수정
---
- upload_image, upload_voice - 설명 추가
- upload_image 업로드 방식 수정
- 채팅 기능으로 Mysql 업로드 추가
---
feat/#20
> [Feat/#20] 채팅 기능 추가 완료 / 이미지 업로드 수정

- app/config/aws/s3Client.py
- app/routers/voices.py
- app/services/image_service.py
- app/services/voice_service.py
- [ 0] Feat(기능 추가)
---
선택한 말풍선번호(redis키) redis에서 키 가지고 s3에 업로드 후 mysql 저장
---
---
> [feat/#22] 선택한 말풍선번호(redis키) redis에서 키 가지고 s3에 업로드 후 mysql 저장

- app/config/elevenlabs/text_to_speech_stream.py
- app/routers/chats.py
- app/services/bubble_service.py
---
GPT로 오는 글자 청크 마다 전송
elevenLabs의 음성 데이터 청크를 바로 전송
---
json 형태로 담아서, 음성, 텍스트를 전송하는 방식으로 제작
---
Feat/#24
> [Feat/#24] GPT 스트림 음성 완 - 비동기 처리 완료

- app/routers/api.py
- app/routers/tests.py
- app/routers/voices.py
테스트 용 api 태그 분리
---
테스트 api url 리팩토링
---
테스트 용 api 태그 분리
---
> [refactor/#25] 테스트 api url 리팩토링

- app/main.py
- app/routers/api.py
- app/routers/chats.py
- app/routers/images.py
- app/routers/tests.py
- app/routers/voices.py
---
API docs 수정 및 사용하지 않는 코드 삭제
---
- API docs 설명 추가
- 사용하지 않는 import 삭제
---
> [refactor/#26] API docs 수정 및 사용하지 않는 코드 삭제

- app/config/elevenlabs/text_to_speech_stream.py
- app/services/bubble_service.py
- app/test/anyioTest.py
---
tts 버그 수정
---
오류 발생시 오류 메시지 출력 문제
---
bug/#27
> [bug/#27] tts 버그 수정

- app/routers/chats.py
- app/services/bubble_service.py
---
버블 생성시 채팅방 유효성 확인, 레디스 저장 추가
---
버블 생성시 채팅방 유효성 확인, 레디스 저장 추가
---
feat/#30
> [Feat/#30] 버블 생성시 채팅방 유효성 확인, 레디스 저장 추가

- app/config/aws/s3Client.py
- app/routers/images.py
- app/services/image_service.py
---
발췌 이미지 배경 목록 조회
---
S3에 저장해둔 샘플 배경 목록 조회
---
> [feat/#34] 발췌 이미지 배경 목록 조회

- app/config/langChain/langChainSetting.py
- app/services/bubble_service.py
---
채팅 기능 추가 및 trimmer 일시 주석화
---
stream - bubble_ai의 id 전송 추가
trimmer 비활성화 - 오류로 인해 추가 수정 진행 예쨩
---
feat/#35
> [Feat/#35] 채팅 기능 추가 및 trimmer 일시 주석화

- app/config/langChain/langChainSetting.py
- app/main.py
---
langchain timmer 적용
---
---
> [feat/#38] langchain timmer 적용

- app/config/aws/s3Client.py
- app/models/character.py
- app/schemas/voice.py
- app/services/voice_service.py
---
목소리 목록 조회 character_image 추가
---
- 캐릭터 모델 image_url 추가
- 목소리 목록 조회 response 스키마 character_image 추가
- 이미지 생성 시 샘플 이미지 조회해오는 s3 경로 수정
---
> [feat/#40] 목소리 목록 조회 character_image 추가

- app/routers/voices.py
- app/schemas/voice.py
- app/services/voice_service.py
---
목소리 상세 정보 조회 character_image 추가
---
---
> [feat/#42] 목소리 상세 정보 조회 character_image 추가

- app/models/image.py
- app/models/voice.py
- app/routers/images.py
- app/routers/voices.py
- app/services/image_service.py
- app/services/voice_service.py
- [o ] Feat(기능 추가)
---
다운로드 기능추가
---
---
> [feat/#46] 다운로드 기능 추가 

- app/config/langChain/langChainSetting.py
- app/models/chat.py
- app/routers/tests.py
- app/schemas/chat.py
- app/services/bubble_service.py
- app/services/chat_service.py
- docker-compose.yml
---
채팅방 별 카테고리 분석 기능 구현
---
- 첫 대화 생성 시와 5개의 대화쌍(10개)이 쌓일 때마다 해당 채팅방의 대화 주제를 분석해 갱신함
- 채팅방 상세 조회에서 response 값으로 topic을 추가함
---
> [feat/#45] 채팅방 별 카테고리 분석 기능 구현

- app/routers/characters.py
- app/schemas/character.py
- app/schemas/dashboard.py
- app/services/character_service.py
- app/services/image_service.py
- app/services/voice_service.py
---
대시보드 데이터 조회 api 구현
---
매운맛 지수는 임시로 넣어둔 데이터입니다. 실제 데이터가 아님.
전체 캐릭터 별 비교를 위한 데이터와 캐릭터 별 통계 데이터를 조회하는 api 구현
---
> [feat/#48] 대시보드 데이터 조회 api 구현

- app/main.py
---
CORS 도메인 설정
---
로컬호스트, 도메인 주소
---
> [bug/#50] CORS 도메인 설정

- app/routers/characters.py
- app/routers/chats.py
- app/routers/tests.py
- app/schemas/dashboard.py
- app/services/character_service.py
- app/services/chat_service.py
---
대시보드 spicy 빈도 구현
---
대시보드 마무리
---
> [feat/#52] 대시보드 spicy 구현 후 마무리

- app/services/character_service.py
---
대시보드 spicy 공백 검사 추가
---
---
> [bug/#53] 대시보드 spicy 공백 검사 추가

- app/main.py
- monitoring/grafana/dashboards/dash.json
- monitoring/grafana/dashboards/dashboards.yml
- monitoring/grafana/datasources/datasouce.yml
- monitoring/prometheus/prometheus.yml
> [feat/#47] 데이터소스.yml 대시보드.yml 제이슨 파일

- docker-compose-deploy.yml
- nginx/nginx.conf
---
nginx 적용
---
dos 공격 대비 및
로드 벨런싱 적용
---
feat/#55
> [feat/#55] nginx 적용

- app/schemas/chat.py
---
ChatRoomBase spicy 자료형 float 수정
---
---
> [bug/#57] ChatRoomBase spicy 자료형 float 수정

- app/routers/images.py
- app/routers/voices.py
- monitoring/elk/filebeat/filebeat.yml
- monitoring/elk/logstash/logstash.yml
- monitoring/prometheus/prometheus.yml
> [bug/#59] 앤드포인트 수정 및 모니터링 수정

- app/main.py
- docker-compose-deploy.yml
- monitoring/prometheus/prometheus.yml
- nginx/configs/nginx-blue.conf
- nginx/configs/nginx-green.conf
- nginx/nginx.conf
---
nginx-prometheus-exporter 설정 추가
---
- nginx-prometheus-exporter가 제공한 메트릭 정보를 수집할 수 있도록 prometheus.yml 설정
- nginx-prometheus-exporter를 위한 docker compose 설정
- nginx의 정보를 얻기위해 stub_status 모듈을 활성
---
set/#61
> [set/#61] nginx-prometheus-exporter 설정 추가

- app/models/character.py
- app/schemas/character.py
- app/services/character_service.py
> [feat/#62] feat: description 추가

- app/services/image_service.py
- app/services/voice_service.py
---
Voice, Image 목록 정렬 최신순으로 변경
---
---
> [feat/#64] Voice, Image 목록 정렬 최신순으로 변경

- app/models/character.py
- app/services/image_service.py
- app/services/voice_service.py
> [main] main Merge

- app/routers/voices.py
---
목소리 저장 시 s3 audio_url 반환하도록 변경
---
---
> [feat/#65] 목소리 저장 시 s3 audio_url 반환하도록 변경

- app/routers/voices.py
Reverts 2024-SummerBootcamp-Team/backend#156
> Revert "[feat/#65] 목소리 저장 시 s3 audio_url 반환하도록 변경"

- app/Dockerfile
- docker-compose-deploy.yml
---
---
Timezone 서울 설정
---
app - Dockerfile : TZ 설정 추가
docker-compose : TZ 설정 추가
set/#66
> [set/#66] Timezone 서울 설정

- app/models/voice.py
- app/routers/voices.py
---
사용자 선택 목소리 저장 ResultResponseModel 처리
---
---
> [feat/#67] 사용자 선택 목소리 저장 ResultResponseModel 처리

- app/services/voice_service.py
---
voice schema 누락 수정
---
create_voice에 VoiceDetail을 리턴 값으로 변경
---
bug/#68
> [bug/#68] voice schema 누락 수정

- app/services/bubble_service.py
---
audio stream 누락 문제 해결
---
async_gpt_stream - task가 종료 후의 async_tts_stream의 yield를 테스크가 종료됨에 따라 누락 시키는 오류 수정
---
bug/#70
> [fix/#70] audio stream 누락 문제 해결
